interface ZIF_C_HR237_BOOKING_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZC_HR237_BOOKING,
 CREATE_ZC_HR237_BOOKING        TYPE /BOBF/ACT_KEY VALUE 'E9DB6CE3AAD91EEDBC984C93EF3FFB59',
 DELETE_ZC_HR237_BOOKING        TYPE /BOBF/ACT_KEY VALUE 'E9DB6CE3AAD91EEDBC984C93EF407B59',
 LOCK_ZC_HR237_BOOKING          TYPE /BOBF/ACT_KEY VALUE 'E9DB6CE3AAD91EEDBC984C93EF3F3B59',
 SAVE_ZC_HR237_BOOKING          TYPE /BOBF/ACT_KEY VALUE 'E9DB6CE3AAD91EEDBC984C93EF40FB59',
 UNLOCK_ZC_HR237_BOOKING        TYPE /BOBF/ACT_KEY VALUE 'E9DB6CE3AAD91EEDBC984C93EF3F7B59',
 UPDATE_ZC_HR237_BOOKING        TYPE /BOBF/ACT_KEY VALUE 'E9DB6CE3AAD91EEDBC984C93EF403B59',
 VALIDATE_ZC_HR237_BOOKING      TYPE /BOBF/ACT_KEY VALUE 'E9DB6CE3AAD91EEDBC984C93EF40BB59',
      END OF ZC_HR237_BOOKING,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZC_HR237_BOOKING,
        BEGIN OF LOCK_ZC_HR237_BOOKING,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF LOCK_ZC_HR237_BOOKING,
        BEGIN OF UNLOCK_ZC_HR237_BOOKING,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF UNLOCK_ZC_HR237_BOOKING,
      END OF ZC_HR237_BOOKING,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZC_HR237_BOOKING,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE 'E9DB6CE3AAD91EEDBC984C93EF41DB59',
      END OF ZC_HR237_BOOKING,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZC_HR237_BOOKING,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE 'E9DB6CE3AAD91EEDBC984C93EF3F1B59',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE 'E9DB6CE3AAD91EEDBC984C93EF3EDB59',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE 'E9DB6CE3AAD91EEDBC984C93EF3FDB59',
      END OF ZC_HR237_BOOKING,
      BEGIN OF ZC_HR237_BOOKING_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'E9DB6CE3AAD91EEDBC984C93EF415B59',
      END OF ZC_HR237_BOOKING_LOCK,
      BEGIN OF ZC_HR237_BOOKING_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'E9DB6CE3AAD91EEDBC984C93EF413B59',
      END OF ZC_HR237_BOOKING_MESSAGE,
      BEGIN OF ZC_HR237_BOOKING_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'E9DB6CE3AAD91EEDBC984C93EF417B59',
      END OF ZC_HR237_BOOKING_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZC_HR237_BOOKING,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZC_HR237_BOOKING,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE 'E9DB6CE3AAD91EEDBC984C93EF3E3B59' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZC_HR237_BOOKING' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZC_HR237_BOOKING,
 BOOK_FILL_TECH_INFO            TYPE /BOBF/DET_KEY VALUE 'E9DB6CE3AAD91EDDBC9A49DD6D833984',
      END OF ZC_HR237_BOOKING,
    END OF SC_DETERMINATION .
  constants:
    BEGIN OF SC_GROUP,
 ZC_HR237_BOOKING               TYPE /BOBF/OBM_GROUP_KEY VALUE 'E9DB6CE3AAD91EEDBC98556FEB979BD6',
    END OF SC_GROUP .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZC_HR237_BOOKING               TYPE /BOBF/OBM_NODE_KEY VALUE 'E9DB6CE3AAD91EEDBC984C93EF3E7B59',
 ZC_HR237_BOOKING_LOCK          TYPE /BOBF/OBM_NODE_KEY VALUE 'E9DB6CE3AAD91EEDBC984C93EF3EFB59',
 ZC_HR237_BOOKING_MESSAGE       TYPE /BOBF/OBM_NODE_KEY VALUE 'E9DB6CE3AAD91EEDBC984C93EF3EBB59',
 ZC_HR237_BOOKING_PROPERTY      TYPE /BOBF/OBM_NODE_KEY VALUE 'E9DB6CE3AAD91EEDBC984C93EF3FBB59',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZC_HR237_BOOKING,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  DATUM                          TYPE STRING VALUE 'DATUM',
  PERNR                          TYPE STRING VALUE 'PERNR',
  PLACE_ID                       TYPE STRING VALUE 'PLACE_ID',
  CREATE_BY                      TYPE STRING VALUE 'CREATE_BY',
  CREATED_WHEN                   TYPE STRING VALUE 'CREATED_WHEN',
      END OF ZC_HR237_BOOKING,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZC_HR237_BOOKING,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE 'E9DB6CE3AAD91EEDBC984C93EF3E9B59',
      END OF ZC_HR237_BOOKING,
    END OF SC_NODE_CATEGORY .
  constants:
    BEGIN OF SC_VALIDATION,
      BEGIN OF ZC_HR237_BOOKING,
 CHECK_DESK_BOOKED              TYPE /BOBF/VAL_KEY VALUE 'E9DB6CE3AAD91EEDBC98556FEB973BD6',
      END OF ZC_HR237_BOOKING,
    END OF SC_VALIDATION .
endinterface.
