interface ZIF_C_HR237_ROOM_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZC_HR237_ROOM,
 CREATE_ZC_HR237_ROOM           TYPE /BOBF/ACT_KEY VALUE 'E9DB6CE3AAD91EDDBBFDA7E13E34414A',
 DELETE_ZC_HR237_ROOM           TYPE /BOBF/ACT_KEY VALUE 'E9DB6CE3AAD91EDDBBFDA7E13E34C14A',
 LOCK_ZC_HR237_ROOM             TYPE /BOBF/ACT_KEY VALUE 'E9DB6CE3AAD91EDDBBFDA7E13E33814A',
 SAVE_ZC_HR237_ROOM             TYPE /BOBF/ACT_KEY VALUE 'E9DB6CE3AAD91EDDBBFDA7E13E35414A',
 UNLOCK_ZC_HR237_ROOM           TYPE /BOBF/ACT_KEY VALUE 'E9DB6CE3AAD91EDDBBFDA7E13E33C14A',
 UPDATE_ZC_HR237_ROOM           TYPE /BOBF/ACT_KEY VALUE 'E9DB6CE3AAD91EDDBBFDA7E13E34814A',
 VALIDATE_ZC_HR237_ROOM         TYPE /BOBF/ACT_KEY VALUE 'E9DB6CE3AAD91EDDBBFDA7E13E35014A',
      END OF ZC_HR237_ROOM,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZC_HR237_ROOM,
        BEGIN OF LOCK_ZC_HR237_ROOM,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF LOCK_ZC_HR237_ROOM,
        BEGIN OF UNLOCK_ZC_HR237_ROOM,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF UNLOCK_ZC_HR237_ROOM,
      END OF ZC_HR237_ROOM,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZC_HR237_ROOM,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE 'E9DB6CE3AAD91EDDBBFDA805EC0F814A',
      END OF ZC_HR237_ROOM,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZC_HR237_ROOM,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE 'E9DB6CE3AAD91EDDBBFDA7E13E33614A',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE 'E9DB6CE3AAD91EDDBBFDA7E13E33214A',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE 'E9DB6CE3AAD91EDDBBFDA7E13E34214A',
      END OF ZC_HR237_ROOM,
      BEGIN OF ZC_HR237_ROOM_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'E9DB6CE3AAD91EDDBBFDA7E13E35A14A',
      END OF ZC_HR237_ROOM_LOCK,
      BEGIN OF ZC_HR237_ROOM_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'E9DB6CE3AAD91EDDBBFDA7E13E35814A',
      END OF ZC_HR237_ROOM_MESSAGE,
      BEGIN OF ZC_HR237_ROOM_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'E9DB6CE3AAD91EDDBBFDA7E13E35C14A',
      END OF ZC_HR237_ROOM_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZC_HR237_ROOM,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZC_HR237_ROOM,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE 'E9DB6CE3AAD91EDDBBFDA7E13E32814A' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZC_HR237_ROOM' .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZC_HR237_ROOM                  TYPE /BOBF/OBM_NODE_KEY VALUE 'E9DB6CE3AAD91EDDBBFDA7E13E32C14A',
 ZC_HR237_ROOM_LOCK             TYPE /BOBF/OBM_NODE_KEY VALUE 'E9DB6CE3AAD91EDDBBFDA7E13E33414A',
 ZC_HR237_ROOM_MESSAGE          TYPE /BOBF/OBM_NODE_KEY VALUE 'E9DB6CE3AAD91EDDBBFDA7E13E33014A',
 ZC_HR237_ROOM_PROPERTY         TYPE /BOBF/OBM_NODE_KEY VALUE 'E9DB6CE3AAD91EDDBBFDA7E13E34014A',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZC_HR237_ROOM,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  ROOM_ID                        TYPE STRING VALUE 'ROOM_ID',
  DEPARTMENT                     TYPE STRING VALUE 'DEPARTMENT',
      END OF ZC_HR237_ROOM,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZC_HR237_ROOM,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE 'E9DB6CE3AAD91EDDBBFDA7E13E32E14A',
      END OF ZC_HR237_ROOM,
    END OF SC_NODE_CATEGORY .
endinterface.
