interface ZIF_C_HR237_PLACE_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZC_HR237_PLACE,
 CREATE_ZC_HR237_PLACE          TYPE /BOBF/ACT_KEY VALUE 'E9DB6CE3AAD91EDDBBC6481B5ED85A31',
 DELETE_ZC_HR237_PLACE          TYPE /BOBF/ACT_KEY VALUE 'E9DB6CE3AAD91EDDBBC6481B5ED8DA31',
 LOCK_ZC_HR237_PLACE            TYPE /BOBF/ACT_KEY VALUE 'E9DB6CE3AAD91EDDBBC6481B5ED79A31',
 SAVE_ZC_HR237_PLACE            TYPE /BOBF/ACT_KEY VALUE 'E9DB6CE3AAD91EDDBBC6481B5ED95A31',
 UNLOCK_ZC_HR237_PLACE          TYPE /BOBF/ACT_KEY VALUE 'E9DB6CE3AAD91EDDBBC6481B5ED7DA31',
 UPDATE_ZC_HR237_PLACE          TYPE /BOBF/ACT_KEY VALUE 'E9DB6CE3AAD91EDDBBC6481B5ED89A31',
 VALIDATE_ZC_HR237_PLACE        TYPE /BOBF/ACT_KEY VALUE 'E9DB6CE3AAD91EDDBBC6481B5ED91A31',
      END OF ZC_HR237_PLACE,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZC_HR237_PLACE,
        BEGIN OF LOCK_ZC_HR237_PLACE,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF LOCK_ZC_HR237_PLACE,
        BEGIN OF UNLOCK_ZC_HR237_PLACE,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF UNLOCK_ZC_HR237_PLACE,
      END OF ZC_HR237_PLACE,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZC_HR237_PLACE,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE 'E9DB6CE3AAD91EDDBBC6481B5EDA3A31',
      END OF ZC_HR237_PLACE,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZC_HR237_PLACE,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE 'E9DB6CE3AAD91EDDBBC6481B5ED77A31',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE 'E9DB6CE3AAD91EDDBBC6481B5ED73A31',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE 'E9DB6CE3AAD91EDDBBC6481B5ED83A31',
      END OF ZC_HR237_PLACE,
      BEGIN OF ZC_HR237_PLACE_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'E9DB6CE3AAD91EDDBBC6481B5ED9BA31',
      END OF ZC_HR237_PLACE_LOCK,
      BEGIN OF ZC_HR237_PLACE_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'E9DB6CE3AAD91EDDBBC6481B5ED99A31',
      END OF ZC_HR237_PLACE_MESSAGE,
      BEGIN OF ZC_HR237_PLACE_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'E9DB6CE3AAD91EDDBBC6481B5ED9DA31',
      END OF ZC_HR237_PLACE_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZC_HR237_PLACE,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZC_HR237_PLACE,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE 'E9DB6CE3AAD91EDDBBC6481B5ED69A31' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZC_HR237_PLACE' .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZC_HR237_PLACE                 TYPE /BOBF/OBM_NODE_KEY VALUE 'E9DB6CE3AAD91EDDBBC6481B5ED6DA31',
 ZC_HR237_PLACE_LOCK            TYPE /BOBF/OBM_NODE_KEY VALUE 'E9DB6CE3AAD91EDDBBC6481B5ED75A31',
 ZC_HR237_PLACE_MESSAGE         TYPE /BOBF/OBM_NODE_KEY VALUE 'E9DB6CE3AAD91EDDBBC6481B5ED71A31',
 ZC_HR237_PLACE_PROPERTY        TYPE /BOBF/OBM_NODE_KEY VALUE 'E9DB6CE3AAD91EDDBBC6481B5ED81A31',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZC_HR237_PLACE,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  PLACE_ID                       TYPE STRING VALUE 'PLACE_ID',
  DEPARTMENT                     TYPE STRING VALUE 'DEPARTMENT',
  PLACE_X                        TYPE STRING VALUE 'PLACE_X',
  PLACE_Y                        TYPE STRING VALUE 'PLACE_Y',
      END OF ZC_HR237_PLACE,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZC_HR237_PLACE,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE 'E9DB6CE3AAD91EDDBBC6481B5ED6FA31',
      END OF ZC_HR237_PLACE,
    END OF SC_NODE_CATEGORY .
endinterface.
